# Generated by Django 5.1.1 on 2024-09-13 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="voted_at",
        ),
        migrations.AddField(
            model_name="vote",
            name="voted_on",
            field=models.DateField(default=datetime.date.today, verbose_name="Date"),
        ),
    ]
