# Generated by Django 5.1.1 on 2024-09-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votings", "0003_alter_vote_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="points",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="vote",
            name="rank",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1st"), (2, "2nd"), (3, "3rd")], default=1
            ),
        ),
    ]
