# Generated by Django 5.1.1 on 2024-09-12 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="Date"),
        ),
    ]
