version: '3.8'

services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
        "
    volumes:
      - .:/app
      - sqlite_data:/app/config/db
    ports:
      - "8000:8000"

volumes:
  sqlite_data: